puts "the students of U Wot M8 Academy"
puts "---------------------------------"
puts "Ginger Chav"
puts "Chav Chavington"
puts "Ali G"
puts "Vicky Pollard"
puts "Jeremy Corbyn"
puts "All Fortnite Players"
puts "H-Annibalzz"
puts "Dr Lectoz"
puts "Dex Lex AzluthorZizzle"

print "unfortunately there are 9 students"
